# Generated by Django 3.0.7 on 2020-06-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200617_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение книги'),
        ),
    ]
