# Generated by Django 3.0.7 on 2020-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200618_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО Автора')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ManyToManyField(to='testapp.Writer'),
        ),
    ]
