# Generated by Django 3.0.7 on 2020-06-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20200630_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.ManyToManyField(to='testapp.Writer'),
        ),
    ]
