# Generated by Django 3.0.7 on 2020-07-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
