# Generated by Django 3.0.7 on 2020-07-10 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0013_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказ')),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('Недоступен для заказа', 'Недоступен для заказа'), ('Доставлен', 'Доставлен')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('На складе', 'На складе'), ('Отсутствует на складе', 'Отсутствует на складе')], max_length=25, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
