# Generated by Django 3.0.7 on 2020-07-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20200713_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
