# Generated by Django 3.0.7 on 2020-07-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity_in_stok',
            field=models.IntegerField(default=1, max_length=3, verbose_name='Количество на складе'),
            preserve_default=False,
        ),
    ]
