# Generated by Django 3.0.7 on 2020-07-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_auto_20200723_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
