# Generated by Django 3.0.7 on 2020-07-23 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('home_address', models.CharField(blank=True, max_length=50, verbose_name='Домашний адресс')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('index', models.IntegerField(blank=True, verbose_name='Индекс')),
                ('home_address_2', models.CharField(blank=True, max_length=100, verbose_name='Домашний адресс_1')),
                ('home_address_3', models.CharField(blank=True, max_length=100, verbose_name='Домашний адресс_2')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
