# Generated by Django 3.0.7 on 2020-07-15 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20200713_1035'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Qantity')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_in_cart', to='testapp.Book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='cart.Cart')),
            ],
            options={
                'unique_together': {('cart', 'book')},
            },
        ),
    ]
