# Generated by Django 3.0.7 on 2020-07-24 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_bookincart_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
